export const FETCH_STUDENT_JOBS = 'FETCH_STUDENT_JOBS';
export const FETCH_SELECTED_JOBS = 'FETCH_SELECTED_JOBS';
export const SET_TERM = 'SET_TERM';
export const POST_JOB = 'POST_JOB';
export const CHANGE_FORM = 'CHANGE_FORM';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
