//export default [
    //'Dog-walking',
    //'Tutoring- Spanish',
    //'Home maintenance',
    //'Tutoring- Mathematics',
    //'Cat Sitting',
    //'Plant watering',
    //'Babysitting',
    //'Cooking',
    //'House Cleaning',
    //'Band playing',
    //'Photography',
    //'Other',
//];

export default [
    'Academic Beavers',
    'English Literature tutoring',
    'English Language tutoring',
    'English conversation',
    'French',
    'French conversation',
    'Spanish tutoring',
    'Spanish conversation',
    'Russian tutoring',
    'Russian conversation',
    'Mandarin tutoring',
    'Mandarin conversation',
    'German tutoring',
    'German conversation',
    'Italian tutoring',
    'Italian conversation',
    'Ancient Greek tutoring',
    'Latin tutoring',
    'Mathematics tutoring',
    'Chemistry tutoring',
    'Biology tutoring',
    'Physics tutoring',
    'History tutoring',
    'Philosophy tutoring',
    'Religious Studies tutoring',
    'Business/Management tutoring',
    'Art tutoring',
    'Oxbridge Entrance tutoring',
    'TSA tutoring',
    'Sport Studies tutoring',
    'Politics tutoring',
    'Art History tutoring',
    'Computing tutoring',
    'Domestic Beavers',
    'Dog-Walking',
    'Ironing',
    'House cleaning',
    'Babysitting',
    'House-sitting',
    'Cooking',
    'Flat-packing',
    'Wall painting',
    'Gardening',
    'Sporty Beavers',
    'Cricket coaching',
    'Tennis coaching',
    'Rugby coaching',
    'Football coaching',
    'Swimming coaching',
    'Hockey coaching',
    'Basketball coaching',
    'Netball coaching',
    'Lacrosse coaching',
    'Water Polo coaching',
    'Athletics coaching',
    'Boxing coaching',
    'Squash coaching',
    'Techy Beavers',
    'Website building',
    'App building',
    'Web Design',
    'Programming',
    'IT advice',
    'Musical Beavers',
    'Singing solo performance',
    'Violin solo performance',
    'Cello solo performance',
    'Clarinet solo performance',
    'Trumpet solo performance',
    'Piano solo performance',
    'Flute solo performance',
    'Harp solo performance',
    'Trumpet solo performance',
    'Drum solo performance',
    'String quartet',
    'Orchestra',
    'Choir',
    'Jazz band',
    'Cover band',
    'A Capella group',
    'Artistic Beavers',
    'Portrait painting',
    'Portrait drawing',
    'Landscape painting',
    'Landscape drawing',
    'Other painting',
    'Other drawing',
    'Party photography',
    'Personal photography',
    'Video making',
    'Other media',
];
