export default [
    {label: 'Academic Beavers', value: 'Academic Beavers', disabled: true},
    {
        label: 'English Literature tutoring',
        value: 'English Literature tutoring',
    },
    {label: 'English Language tutoring', value: 'English Language tutoring'},
    {label: 'English conversation', value: 'English conversation'},
    {label: 'French', value: 'French'},
    {label: 'French conversation', value: 'French conversation'},
    {label: 'Spanish tutoring', value: 'Spanish tutoring'},
    {label: 'Spanish conversation', value: 'Spanish conversation'},
    {label: 'Russian tutoring', value: 'Russian tutoring'},
    {label: 'Russian conversation', value: 'Russian conversation'},
    {label: 'Mandarin tutoring', value: 'Mandarin tutoring'},
    {label: 'Mandarin conversation', value: 'Mandarin conversation'},
    {label: 'German tutoring', value: 'German tutoring'},
    {label: 'German conversation', value: 'German conversation'},
    {label: 'Italian tutoring', value: 'Italian tutoring'},
    {label: 'Italian conversation', value: 'Italian conversation'},
    {label: 'Ancient Greek tutoring', value: 'Ancient Greek tutoring'},
    {label: 'Latin tutoring', value: 'Latin tutoring'},
    {label: 'Mathematics tutoring', value: 'Mathematics tutoring'},
    {label: 'Chemistry tutoring', value: 'Chemistry tutoring'},
    {label: 'Biology tutoring', value: 'Biology tutoring'},
    {label: 'Physics tutoring', value: 'Physics tutoring'},
    {label: 'History tutoring', value: 'History tutoring'},
    {label: 'Philosophy tutoring', value: 'Philosophy tutoring'},
    {label: 'Religious Studies tutoring', value: 'Religious Studies tutoring'},
    {
        label: 'Business/Management  tutoring',
        value: 'Business/Management  tutoring',
    },
    {label: 'Art tutoring', value: 'Art tutoring'},
    {label: 'Oxbridge Entrance tutoring', value: 'Oxbridge Entrance tutoring'},
    {label: 'TSA tutoring', value: 'TSA tutoring'},
    {label: 'Sport Studies tutoring', value: 'Sport Studies tutoring'},
    {label: 'Politics tutoring', value: 'Politics tutoring'},
    {label: 'Art History tutoring', value: 'Art History tutoring'},
    {label: 'Computing tutoring', value: 'Computing tutoring'},
    {label: 'Domestic Beavers', value: 'Domestic Beavers', disabled: true},
    {label: 'Dog-Walking', value: 'Dog-Walking'},
    {label: 'Ironing', value: 'Ironing'},
    {label: 'House cleaning ', value: 'House cleaning '},
    {label: 'Babysitting', value: 'Babysitting'},
    {label: 'House- }sitting', value: 'House- }sitting'},
    {label: 'Cooking', value: 'Cooking'},
    {label: 'Flat- }packing', value: 'Flat- }packing'},
    {label: 'Wall painting', value: 'Wall painting'},
    {label: 'Gardening', value: 'Gardening'},
    {label: 'Sporty Beavers ', value: 'Sporty Beavers', disabled: true},
    {label: 'Cricket coaching', value: 'Cricket coaching'},
    {label: 'Tennis coaching', value: 'Tennis coaching'},
    {label: 'Rugby coaching', value: 'Rugby coaching'},
    {label: 'Football coaching', value: 'Football coaching'},
    {label: 'Swimming coaching', value: 'Swimming coaching'},
    {label: 'Hockey coaching', value: 'Hockey coaching'},
    {label: 'Basketball coaching', value: 'Basketball coaching'},
    {label: 'Netball coaching', value: 'Netball coaching'},
    {label: 'Lacrosse coaching', value: 'Lacrosse coaching'},
    {label: 'Water Polo coaching', value: 'Water Polo coaching'},
    {label: 'Athletics coaching', value: 'Athletics coaching'},
    {label: 'Boxing coaching', value: 'Boxing coaching'},
    {label: 'Squash coaching', value: 'Squash coaching'},
    {label: 'Techy Beavers', value: 'Techy Beavers', disabled: true},
    {label: 'Website building', value: 'Website building'},
    {label: 'App building', value: 'App building'},
    {label: 'Web Design', value: 'Web Design'},
    {label: 'Programming', value: 'Programming'},
    {label: 'IT advice ', value: 'IT advice'},
    {label: 'Musical Beavers', value: 'Musical Beavers', disabled: true},
    {label: 'Singing solo performance', value: 'Singing solo performance'},
    {label: 'Violin solo performance', value: 'Violin solo performance'},
    {label: 'Cello solo performance', value: 'Cello solo performance'},
    {label: 'Clarinet solo performance', value: 'Clarinet solo performance'},
    {label: 'Trumpet solo performance', value: 'Trumpet solo performance'},
    {label: 'Piano solo performance', value: 'Piano solo performance'},
    {label: 'Flute solo performance', value: 'Flute solo performance'},
    {label: 'Harp solo performance', value: 'Harp solo performance'},
    {label: 'Trumpet solo performance', value: 'Trumpet solo performance'},
    {label: 'Drum solo performance', value: 'Drum solo performance'},
    {label: 'String quartet', value: 'String quartet'},
    {label: 'Orchestra', value: 'Orchestra'},
    {label: 'Choir', value: 'Choir'},
    {label: 'Jazz band', value: 'Jazz band'},
    {label: 'Cover band', value: 'Cover band'},
    {label: 'A Capella group', value: 'A Capella group'},
    {label: 'Artistic Beavers', value: 'Artistic Beavers', disabled: true},
    {label: 'Portrait painting', value: 'Portrait painting'},
    {label: 'Portrait drawing', value: 'Portrait drawing'},
    {label: 'Landscape painting', value: 'Landscape painting'},
    {label: 'Landscape drawing', value: 'Landscape drawing'},
    {label: 'Other painting', value: 'Other painting'},
    {label: 'Other drawing', value: 'Other drawing'},
    {label: 'Party photography', value: 'Party photography'},
    {label: 'Personal photography', value: 'Personal photography'},
    {label: 'Video making', value: 'Video making'},
    {label: 'Other media', value: 'Other media'},
];
