const categories = [
    {group: 'Academic Beavers', value: 'English Literature tutoring'},
    {group: 'Academic Beavers', value: 'English Language tutoring'},
    {group: 'Academic Beavers', value: 'English conversation'},
    {group: 'Academic Beavers', value: 'French'},
    {group: 'Academic Beavers', value: 'French conversation'},
    {group: 'Academic Beavers', value: 'Spanish tutoring'},
    {group: 'Academic Beavers', value: 'Spanish conversation'},
    {group: 'Academic Beavers', value: 'Russian tutoring'},
    {group: 'Academic Beavers', value: 'Russian conversation'},
    {group: 'Academic Beavers', value: 'Mandarin tutoring'},
    {group: 'Academic Beavers', value: 'Mandarin conversation'},
    {group: 'Academic Beavers', value: 'German tutoring'},
    {group: 'Academic Beavers', value: 'German conversation'},
    {group: 'Academic Beavers', value: 'Italian tutoring'},
    {group: 'Academic Beavers', value: 'Italian conversation'},
    {group: 'Academic Beavers', value: 'Ancient Greek tutoring'},
    {group: 'Academic Beavers', value: 'Latin tutoring'},
    {group: 'Academic Beavers', value: 'Mathematics tutoring'},
    {group: 'Academic Beavers', value: 'Chemistry tutoring'},
    {group: 'Academic Beavers', value: 'Biology tutoring'},
    {group: 'Academic Beavers', value: 'Physics tutoring'},
    {group: 'Academic Beavers', value: 'History tutoring'},
    {group: 'Academic Beavers', value: 'Philosophy tutoring'},
    {group: 'Academic Beavers', value: 'Religious Studies tutoring'},
    {group: 'Academic Beavers', value: 'Business/Management  tutoring'},
    {group: 'Academic Beavers', value: 'Art tutoring'},
    {group: 'Academic Beavers', value: 'Oxbridge Entrance tutoring'},
    {group: 'Academic Beavers', value: 'TSA tutoring'},
    {group: 'Academic Beavers', value: 'Sport Studies tutoring'},
    {group: 'Academic Beavers', value: 'Politics tutoring'},
    {group: 'Academic Beavers', value: 'Art History tutoring'},
    {group: 'Academic Beavers', value: 'Computing tutoring'},
    {group: 'Domestic Beavers', value: 'Dog-Walking'},
    {group: 'Domestic Beavers', value: 'Ironing'},
    {group: 'Domestic Beavers', value: 'House cleaning '},
    {group: 'Domestic Beavers', value: 'Babysitting'},
    {group: 'Domestic Beavers', value: 'House-sitting'},
    {group: 'Domestic Beavers', value: 'Cooking'},
    {group: 'Domestic Beavers', value: 'Flat-packing'},
    {group: 'Domestic Beavers', value: 'Wall painting'},
    {group: 'Domestic Beavers', value: 'Gardening'},
    {group: 'Domestic Beavers', value: 'Sporty Beavers'},
    {group: 'Domestic Beavers', value: 'Cricket coaching'},
    {group: 'Domestic Beavers', value: 'Tennis coaching'},
    {group: 'Domestic Beavers', value: 'Rugby coaching'},
    {group: 'Domestic Beavers', value: 'Football coaching'},
    {group: 'Domestic Beavers', value: 'Swimming coaching'},
    {group: 'Domestic Beavers', value: 'Hockey coaching'},
    {group: 'Domestic Beavers', value: 'Basketball coaching'},
    {group: 'Domestic Beavers', value: 'Netball coaching'},
    {group: 'Domestic Beavers', value: 'Lacrosse coaching'},
    {group: 'Domestic Beavers', value: 'Water Polo coaching'},
    {group: 'Domestic Beavers', value: 'Athletics coaching'},
    {group: 'Domestic Beavers', value: 'Boxing coaching'},
    {group: 'Domestic Beavers', value: 'Squash coaching'},
    {group: 'Techy Beavers', value: 'Website building'},
    {group: 'Techy Beavers', value: 'App building'},
    {group: 'Techy Beavers', value: 'Web Design'},
    {group: 'Techy Beavers', value: 'Programming'},
    {group: 'Techy Beavers', value: 'IT advice'},
    {group: 'Musical Beavers', value: 'Singing solo performance'},
    {group: 'Musical Beavers', value: 'Violin solo performance'},
    {group: 'Musical Beavers', value: 'Cello solo performance'},
    {group: 'Musical Beavers', value: 'Clarinet solo performance'},
    {group: 'Musical Beavers', value: 'Trumpet solo performance'},
    {group: 'Musical Beavers', value: 'Piano solo performance'},
    {group: 'Musical Beavers', value: 'Flute solo performance'},
    {group: 'Musical Beavers', value: 'Harp solo performance'},
    {group: 'Musical Beavers', value: 'Trumpet solo performance'},
    {group: 'Musical Beavers', value: 'Drum solo performance'},
    {group: 'Musical Beavers', value: 'String quartet'},
    {group: 'Musical Beavers', value: 'Orchestra'},
    {group: 'Musical Beavers', value: 'Choir'},
    {group: 'Musical Beavers', value: 'Jazz band'},
    {group: 'Musical Beavers', value: 'Cover band'},
    {group: 'Musical Beavers', value: 'A Capella group'},
    {group: 'Artistic Beavers', value: 'Portrait painting'},
    {group: 'Artistic Beavers', value: 'Portrait drawing'},
    {group: 'Artistic Beavers', value: 'Landscape painting'},
    {group: 'Artistic Beavers', value: 'Landscape drawing'},
    {group: 'Artistic Beavers', value: 'Other painting'},
    {group: 'Artistic Beavers', value: 'Other drawing'},
    {group: 'Artistic Beavers', value: 'Party photography'},
    {group: 'Artistic Beavers', value: 'Personal photography'},
    {group: 'Artistic Beavers', value: 'Video making'},
    {group: 'Artistic Beavers', value: 'Other media'},
];

export default categories;
